services:
  # Rest api service
  api-server:
    build: 
      context: ./api
      args:
        - INTERNAL_GATEWAY=${INTERNAL_GATEWAY}
    ports:
      - 8080:8080
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://user:pass@mongodb:27017/?authMechanism=DEFAULT&directConnection=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CERTS_DIR=/tmp/hyperledger
      - PRODUCTION=true
    volumes:
      - ${ARTIFACTS_DIR}:/tmp/hyperledger
    networks:
      - blockchain_fabric-ca
      - backend
    depends_on:
      - verdaccio
    links:
      - mongodb
      - redis
      - verdaccio

  # Authentication service
  auth-server:
    build: 
      context: ./auth
      args:
        - INTERNAL_GATEWAY=${INTERNAL_GATEWAY}
    ports:
      - 8180:8180
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://user:pass@mongodb:27017/?authMechanism=DEFAULT&directConnection=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PRODUCTION=true
    networks:
      - backend
    depends_on:
      - verdaccio
    links:
      - mongodb
      - redis
      - verdaccio

  # Mongodb service
  mongodb:
    image: mongodb/mongodb-community-server:4.4.12-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./dbdata
        target: /data/db
    networks:
      - backend

  # Private npm registry
  verdaccio:
    image: verdaccio/verdaccio:5
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - 4873:4873
    expose:
      - 4873
    volumes:
      - ./verdaccio/storage:/verdaccio/storage
      - ./verdaccio/conf:/verdaccio/conf
      - ./verdaccio/plugins:/verdaccio/plugins
    networks:
      - backend

# Redis service, used for api rate limiting
  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - type: bind
        source: ./cache
        target: /data
    networks:
      - backend

networks:
  blockchain_fabric-ca:
    external: true
  backend:

