[versions]
junit = "5.10.1"
log4j = "2.20.0"

[libraries]
fabric-chaincode-shim = "org.hyperledger.fabric-chaincode-java:fabric-chaincode-shim:2.5.0"
genson = "com.owlike:genson:1.6"
json = "org.json:json:20231013"
commons-lang = "org.apache.commons:commons-lang3:3.14.0"
guava = "com.google.guava:guava:32.1.3-jre"
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
assertj-core = "org.assertj:assertj-core:3.25.2"
mockito-core = "org.mockito:mockito-core:5.10.0"
spotbugs-annotations = "com.github.spotbugs:spotbugs-annotations:4.8.3"
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j-impl = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }

[plugins]
java-qa = "org.danilopianini.gradle-java-qa:1.36.0"
shadowJar = "com.github.johnrengelman.shadow:8.1.1"
